[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Python-Base"
version = "0.1.0"
description = "Python-Base"
requires-python = ">=3.14"
dependencies = [
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[project.scripts]
protoproject = "cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pylint.basic]
no-docstring-rgx = "^(_|test_.*|setUp|tearDown|setUpClass|tearDownClass|Test.*|.*Tests)$"
